# .github/workflows/gpt-translate.yml
name: GPT Translate

on:
  issue_comment:
    types: [ created ]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run GPT Translate
        if: |
          contains(github.event.comment.body, '/gt')
        uses: jiaqiwang969/gpt-translate@main
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-3.5-turbo-16k"
          prompt: "I am translating the documentation for solidworks-api,Translate the Markdown content I'll paste. You must strictly follow the rules below. 1. Never change the Markdown markup structure. Don't add or remove links. Do not change any URL. 2. Never change the contents of code blocks even if they appear to have a bug. 3. Always preserve the original line breaks. Do not add or remove blank lines. 4. Never touch the permalink such as {/*examples*/} at the end of each heading. 5. Never touch HTML-like tags such as <Notes>."
