# .github/workflows/gpt-translate.yml
name: GPT Translate

on:
  issue_comment:
    types: [ created ]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run GPT Translate
        if: |
          contains(github.event.comment.body, '/gt')
        uses: 3ru/gpt-translate@feat/web-i18n
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-3.5-turbo-16k"
